
- name: ensure rbac directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/kubernetes/halcyon/"
    - "/etc/kubernetes/halcyon/rbac"

- name: copy rbac template
  copy:
    src: templates/rbac.yaml
    dest: /etc/kubernetes/halcyon/rbac/rbac.yaml
    owner: root
    group: root
    mode: 0644

- name: deploy cluster rbac
  shell: "kubectl replace -f /etc/kubernetes/halcyon/rbac/rbac.yaml"
  register: deploy_rbac

- name: rbac deployment stdout
  debug: msg={{ deploy_rbac }}

- pause:
    prompt: "Make sure kubectl work"
  when: debug_kubectl
